###Добавить вопрос
GET http://localhost:8080/exam/java/add?question=QuestionText&answer=QuestionAnswer
###Добавить вопрос
GET http://localhost:8080/exam/java/add?question=QuestionText1&answer=QuestionAnswer1
###Добавить вопрос
GET http://localhost:8080/exam/java/add?question=QuestionText2&answer=QuestionAnswer2
###Добавить вопрос
GET http://localhost:8080/exam/java/add?question=QuestionText3&answer=QuestionAnswer3
###Удалить вопрос
GET http://localhost:8080/exam/java/remove?question=QuestionText&answer=QuestionAnswer
###Получить все вопросы
GET http://localhost:8080/exam/java